export const ACTION_STORE_USER_EMAIL = 'STORE_USER_EMAIL';
export const ACTION_STORE_USER_PASSWORD = 'STORE_USER_PASSWORD';
export const ACTION_CHECK_USER_EMAIL = 'CHECK_USE_EMAIL';
export const ACTION_CHECK_USER_PASSWORD = 'CHECK_USER_PASSWORD';